export const REQUEST_CATEGORIES = {
  SOFTWARE: "SOFTWARE",
  WEB_DEVELOPMENT: "WEB_DEVELOPMENT",
  MOBILE_DEVELOPMENT: "MOBILE_DEVELOPMENT",
  NETWORKING: "NETWORKING",
  ELECTRICAL: "ELECTRICAL",
  ELECTRONICS: "ELECTRONICS",
  MECHANICAL: "MECHANICAL",
  AGRICULTURE: "AGRICULTURE",
  CONSTRUCTION: "CONSTRUCTION",
  MANUFACTURING: "MANUFACTURING",
  ENERGY: "ENERGY",
  AUTOMATION: "AUTOMATION",
  DESIGN: "DESIGN",
  OTHER: "OTHER"
} as const;

export type RequestCategory = (typeof REQUEST_CATEGORIES)[keyof typeof REQUEST_CATEGORIES];

export const URGENCY_LEVELS = {
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  URGENT: "URGENT"
} as const;

export type UrgencyLevel = (typeof URGENCY_LEVELS)[keyof typeof URGENCY_LEVELS];
