export const REQUEST_STATUSES = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  NEEDS_INFORMATION: "NEEDS_INFORMATION",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  MATCHING: "MATCHING",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  TESTING: "TESTING",
  AWAITING_CLIENT_FEEDBACK: "AWAITING_CLIENT_FEEDBACK",
  REVISION_REQUIRED: "REVISION_REQUIRED",
  READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
} as const;

export type RequestStatus = (typeof REQUEST_STATUSES)[keyof typeof REQUEST_STATUSES];

const { DRAFT, SUBMITTED, UNDER_REVIEW, NEEDS_INFORMATION, ACCEPTED, REJECTED, MATCHING, ASSIGNED, IN_PROGRESS, TESTING, AWAITING_CLIENT_FEEDBACK, REVISION_REQUIRED, READY_FOR_DELIVERY, DELIVERED, COMPLETED, CANCELLED } =
  REQUEST_STATUSES;

export const REQUEST_TRANSITIONS: Record<RequestStatus, readonly RequestStatus[]> = {
  DRAFT: [SUBMITTED, CANCELLED],
  SUBMITTED: [UNDER_REVIEW, CANCELLED],
  UNDER_REVIEW: [ACCEPTED, REJECTED, NEEDS_INFORMATION, CANCELLED],
  NEEDS_INFORMATION: [SUBMITTED, CANCELLED],
  ACCEPTED: [MATCHING, CANCELLED],
  REJECTED: [],
  MATCHING: [ASSIGNED, CANCELLED],
  ASSIGNED: [IN_PROGRESS, CANCELLED],
  IN_PROGRESS: [TESTING, CANCELLED],
  TESTING: [AWAITING_CLIENT_FEEDBACK, CANCELLED],
  AWAITING_CLIENT_FEEDBACK: [REVISION_REQUIRED, READY_FOR_DELIVERY, CANCELLED],
  REVISION_REQUIRED: [IN_PROGRESS, CANCELLED],
  READY_FOR_DELIVERY: [DELIVERED, CANCELLED],
  DELIVERED: [COMPLETED],
  COMPLETED: [],
  CANCELLED: []
};

export function canTransition(from: RequestStatus, to: RequestStatus): boolean {
  return REQUEST_TRANSITIONS[from].includes(to);
}
